////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Development

{project-name} uses {project-github-url}[GitHub] for source code management.

The project requires a Java compiler matching the `{java-compiler-version}` range and targets Java `{java-target-version}`.

You can build and verify sources using:

[source,bash]
----
./mvnw verify
----

You can build and view the website as follows:

[source,bash]
----
./mvnw -N site
----

You can view the generated website with a browser by pointing it to `target/site` directory.

[#release-instructions]
== Release instructions

{project-name} employs the CI/CD foundation provided by the {logging-services-url}/logging-parent[`logging-parent`].
You can simply use its release instructions.
