////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#development]
= Development

{project-name} uses {project-github-url}[GitHub] for source code management.

[#building]
== Building log4net

Log4net provides support for the following targets

* net462
* netstandard2.0

[#windows]
=== Windows
* install Visual Studio Build Tools (at least VS 2022)
* install dotnet (v8+) and the .NET SDK (current latest)
* in the project folder
+
[source,powershell]
----
dotnet test ./src/log4net.sln
----

[#docker]
=== Docker
* install docker (if you haven't already)
** https://docs.docker.com/engine/install/
* in logging/log4net run
+
[source,bash]
----
docker build -t log4net-builder .
docker run -it log4net-builder
----
** this will
*** install all dependencies in the container
*** build src/log4net.sln
* inside the container run
+
[source,bash]
----
dotnet test /logging-log4net/src/log4net.sln
----

[#linux-macos]
=== Linux / MacOS
- install the dotnet SDK - v8 or better
- install Mono (you're going to need it to target certain versions of .NET)

[#site]
== Site
You can build and view the website as follows:

[source,bash/powershell]
----
./mvnw -N site
----

You can view the generated website with a browser by pointing it to `target/site` directory.

[#release-instructions]
== Release instructions

{project-name} employs the CI/CD foundation provided by the {logging-services-url}/logging-parent[`logging-parent`].
You can simply use its release instructions.
