////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#features]
= Features

[#overview]
== Overview
log4net is a tool to help the programmer output log statements to a variety of output targets.
In case of problems with an application, it is helpful to enable logging so that the problem can be located.
With log4net it is possible to enable logging at runtime without modifying the application binary.
The log4net package is designed so that log statements can remain in shipped code without incurring a high performance cost.
It follows that the speed of logging (or rather not logging) is crucial.

At the same time, log output can be so voluminous that it quickly becomes overwhelming.
One of the distinctive features of log4net is the notion of hierarchical loggers.
Using these loggers it is possible to selectively control which log statements are output at arbitrary granularity.

log4net is designed with two distinct goals in mind: speed and flexibility

[#featurelist]
== Features
* Support for multiple frameworks
* Output to multiple logging targets
* Hierarchical logging architecture
* XML Configuration
* Dynamic Configuration
* Logging Context
* Proven architecture
* Modular and extensible design
* High performance with flexibility

[#frameworks]
== Support for multiple frameworks
log4net has specific builds for the following frameworks:

* .NET Core 8 or higher - using netstandard-2.0
* Microsoft .NET Framework 4.6.2 or higher

[#appenders]
== Output to multiple logging targets
log4net ships with the following appenders
[cols="Type,Description"]
|===
|Type |Description

|xref:manual/configuration/appenders/adonetappender.adoc[]
|Writes logging events to a database using either prepared statements or stored procedures.

|AnsiColorTerminalAppender
|Writes color highlighted logging events to a an ANSI terminal window.

|AspNetTraceAppender
|Writes logging events to the ASP trace context. These can then be rendered at the end of the ASP page or on the ASP trace page.

|xref:manual/configuration/appenders/bufferingforwardingappender.adoc[]
|Buffers events and then forwards them to attached appenders.

|xref:manual/configuration/appenders/consoleappender.adoc[]
|Writes color highlighted logging events to the application's Windows Console.

|ConsoleAppender
|Writes logging events to the application's Console.
The events may go to either the standard our stream or the standard error stream.

|DebugAppender
|Writes logging events to the .net debugger (https://web.archive.org/web/20240930165834/https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug?view=net-8.0[System.Diagnostics.Debug]).

|xref:manual/configuration/appenders/eventlogappender.adoc[]
|Writes logging events to the Windows Event Log.

|xref:manual/configuration/appenders/fileappender.adoc[]
|Writes logging events to a file in the file system.

|xref:manual/configuration/appenders/localsyslogappender.adoc[]
|Writes logging events to the local https://datatracker.ietf.org/doc/html/rfc3164[syslog] service (UNIX only).

|xref:manual/configuration/appenders/managedcoloredconsoleappender.adoc[]
|Writes color highlighted logging events to the application's Windows Console.
This appender is a managed version of the ColoredConsoleAppender and does not require the use of the Windows Console API.
It is a replacement for the ColoredConsoleAppender and is the recommended appender for logging to the Console.

|xref:manual/configuration/appenders/memoryappender.adoc[]
|Stores logging events in an in memory buffer.

|xref:manual/configuration/appenders/outputdebugstringappender.adoc[]
|Writes logging events to the debugger (using https://web.archive.org/web/20241118170546/https://learn.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-outputdebugstringw[OutputDebugString]).
If the application has no debugger, the system debugger displays the string.
If the application has no debugger and the system debugger is not active, the message is ignored.

|xref:manual/configuration/appenders/remotesyslogappender.adoc[]
|Writes logging events to a remote https://datatracker.ietf.org/doc/html/rfc3164[syslog] service using UDP networking.

|xref:manual/configuration/appenders/rollingfileappender.adoc[]
|Writes logging events to a file in the file system.
The RollingFileAppender can be configured to log to multiple files based upon date or file size constraints.

|xref:manual/configuration/appenders/smtpappender.adoc[]
|Sends logging events to an email address.

|xref:manual/configuration/appenders/smtppickupdirappender.adoc[]
|Sends logging events to an email address but writes the emails to a configurable directory rather than sending them directly via SMTP.

|TelnetAppender
|*Clients* connect via Telnet to receive logging events.

|xref:manual/configuration/appenders/traceappender.adoc[]
|Writes logging events to the .NET trace system (https://web.archive.org/web/20240907024634/https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.trace?view=net-8.0[System.Diagnostics.Trace]).

|xref:manual/configuration/appenders/udpappender.adoc[]
|Sends logging events as connectionless UDP datagrams to a remote host or a multicast group using a UdpClient.

|xref:manual/configuration/appenders/forwardingappender.adoc[]
|Can be used to wrap another appender, for example to attach additional filters.

|===

[#hierarchy]
== Hierarchical logging architecture
Hierarchical logging is an ideal fit with component based development.
Each component has its own of logger.
When individually tested, the properties of these loggers may be set as the developer requires.
When combined with other components, the loggers inherit the properties determined by the integrator of the components.
One can selectively elevate logging priorities on one component without affecting the other components.
This is useful when you need a detailed trace from just a single component without crowding the trace file with messages from other components.
All this can be done through configuration files - no code changes are required.

[#xml-config]
== XML Configuration
log4net is configured using an XML configuration file.
The configuration information can be embedded within other XML configuration files (such as the application's .config file) or in a separate file.
The configuration is easily readable and updateable while retaining the flexibility to express all configurations.

Alternatively log4net can be configured programmatically.

[#dynamic-config]
== Dynamic Configuration
log4net can monitor its configuration file for changes and dynamically apply changes made by the configurator.
The logging levels, appenders, layouts, and just about everything else can be adjusted at runtime.
In many cases it is possible to diagnose application issues without terminating the process in question.
This can a very valuable tool in investigating issues with deployed applications.