////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

= Log4j Docgen Maven Plugin

Log4j Docgen Maven Plugin allows you to easily run Log4j Docgen xref:log4j-docgen.adoc#documentation-generator[documentation generator] and xref:log4j-docgen.adoc#schema-generator[schema generator] from your `pom.xml`.

[#dependencies]
== Dependencies

You need to have the `org.apache.logging.log4j:log4j-docgen-maven-plugin` dependency in your classpath:

[source,xml,subs="+attributes"]
----
<plugin>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-docgen-maven-plugin</artifactId>
  <version>{project-version}</version>
</plugin>
----

[#generate-documentation]
== Generate documentation

The `generate-documentation` goal generates an AsciiDoc-formatted documentation using FreeMarker templates that are fed with the types loaded from given descriptors:

.An example `log4j-docgen:generate-documentation` configuration
[source,xml,subs="+attributes"]
----
<configuration>

  <descriptorFileMatchers>
    <descriptorFileMatcher>
      <baseDirectory>${project.build.directory}/plugin-descriptors</baseDirectory>
    </descriptorFileMatcher>
  </descriptorFileMatchers>

  <typeFilter>
    <excludes>
      <exclude>^java\..+</exclude>
    </excludes>
  </typeFilter>

  <templateDirectory>${project.basedir}/src/docgen-templates</templateDirectory>

  <indexTemplates>
    <template>
      <source>index.adoc.ftl</source>
      <target>${project.build.directory}/generated-site/asciidoc/plugin-reference/index.adoc</target>
    </template>
  </indexTemplates>

  <typeTemplates>
    <template>
      <source>type.adoc.ftl</source>
      <target>${project.build.directory}/generated-site/asciidoc/plugin-reference/%g/%a/%c.adoc</target><!--1-->
    </template>
  </typeTemplates>

</configuration>
----
<1> `target` must be in sync. with xref:log4j-docgen-asciidoctor-extension.adoc#log4j-docgen-type-target-template[the `log4j-docgen-type-target-template` configuration of `log4j-docgen-asciidoctor-extension`].

The `generate-documentation` goal configuration also accepts the following parameters:

`skip` (parameter)::
Indicates if the execution should be skipped or not.
It defaults to `false` and can be set using the `log4j.docgen.skip` property.

[#generate-schema]
== Generate schema

The `generate-schema` goal generates an XSD derived from the types loaded using given descriptors:

.An example `log4j-docgen:generate-schema` configuration
[source,xml,subs="+attributes"]
----
<configuration>

  <descriptorFileMatchers>
    <descriptorFileMatcher>
      <baseDirectory>${project.build.directory}/plugin-descriptors</baseDirectory>
    </descriptorFileMatcher>
  </descriptorFileMatchers>

  <typeFilter>
    <excludes>
      <exclude>^java\..+</exclude>
    </excludes>
  </typeFilter>

  <schemaVersion>${project.version}</schemaVersion>
  <schemaFile>${project.build.directory}/generated-site/resources/config.xsd</schemaFile>

</configuration>
----

The `generate-schema` goal configuration also accepts the following parameters:

`skip` (parameter)::
Indicates if the execution should be skipped or not.
It defaults to `false` and can be set using the `log4j.docgen.skip` property.
