////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

= Log4j Docgen

Log4j Docgen (Documentation Generation) bundles utility classes to generate documentation from Log4j plugins.
Given almost all Log4j functionality (layouts, appenders, etc.) is implemented in the form of plugins, this project aims the following goals:

Avoid the need to maintain documentation in multiple places::
For instance, Log4j JSON Template Layout is composed of several plugins with sufficient Javadoc explaining their behaviour.
Next to this we also maintain a big `json-template-layout.adoc` page for the website, again, documenting each component.
By generating documentation from the source code, developers can precisely capture the behaviour of their components only in the very code itself that they change.

Accurately capture the component configuration::
It is pretty common that source code changes are not reflected to documentation.
By generating the documentation from the source code, this discrepancy gets removed.

[#dependencies]
== Dependencies

You need to have the `org.apache.logging.log4j:log4j-docgen` dependency in your classpath:

[source,xml,subs="+attributes"]
----
<plugin>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-docgen</artifactId>
  <version>{project-version}</version>
</plugin>
----

[#descriptor-generator]
== Descriptor generator

`DescriptorGenerator` is an annotation processor that generates an XML file capturing all the metadata needed to document a plugin:

* **types** – types it extends from, types it uses in its configuration, etc.
* **configuration** – extracts the necessary set of elements, attributes, etc. from builder classes, `@PluginFactory`-annotated methods, etc.
* **documentation** – extracts the Javadoc of each field and type, and converts it to AsciiDoc

Users are recommended to integrate this annotation processor into their build:

[source,xml,subs="+attributes"]
----
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <configuration>
    <annotationProcessorPaths combine.children="append">
      <!-- Include `org.apache.logging.log4j.docgen.processor.DescriptorGenerator` that generates `log4j-plugins.xml`.
           `DescriptorGenerator` must precede `PluginProcessor`, since the latter *claims* the `@Plugin`.
           Once claimed, `javac` doesn't pass those sources to other processors. -->
      <path>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-docgen</artifactId>
        <version>{project-version}</version>
      </path>
      <!-- `org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor` for generating `META-INF/org/apache/.../Log4j2Plugins.dat`: -->
      <path>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <version>${project.version}</version>
      </path>
    </annotationProcessorPaths>
    <compilerArgs combine.children="append">
      <!-- Provide `org.apache.logging.log4j.docgen.processor.DescriptorGenerator` arguments: -->
      <arg>-Alog4j.docgen.skip=false</arg><!-- optional (defaults to `false`) -->
      <arg>-Alog4j.docgen.descriptorFilePath=${project.build.directory}/${project.artifactId}-plugins.xml</arg>
      <arg>-Alog4j.docgen.groupId=${project.groupId}</arg>
      <arg>-Alog4j.docgen.artifactId=${project.artifactId}</arg>
      <arg>-Alog4j.docgen.version=${project.version}</arg>
      <arg>-Alog4j.docgen.description=${project.description}</arg>
      <arg>-Alog4j.docgen.typeFilter.excludePattern=^java\..+</arg>
    </compilerArgs>
  </configuration>
</plugin>
----

[#documentation-generator]
== Documentation generator

`DocumentationGenerator` receives

. plugin descriptors (generated by the `DescriptorGenerator`)
. FreeMarker templates (to render the type hierarchy and each individual type)

as input arguments, and produces an AsciiDoc-formatted documentation that one can integrate into the website of a project.

Users are recommended to use xref:log4j-docgen-maven-plugin.adoc#generate-documentation[the `generate-documentation` goal of the `log4j-docgen-maven-plugin`] instead.

[#schema-generator]
== Schema generator

`SchemaGenerator` receives plugin descriptors (generated by the `DescriptorGenerator`) as input, and produces an XSD describing the structure defined by the descriptors.

Users are recommended to use xref:log4j-docgen-maven-plugin.adoc#generate-schema[the `generate-schema` goal of the `log4j-docgen-maven-plugin`] instead.
