////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[#appenders]
= Appenders

Appenders are responsible for delivering log events to their destination.
Every Appender must implement the `IAppender` interface.

While not strictly required by the log4net architecture, most appenders inherit from `AppenderSkeleton` and:

* delegate the filtering of log events to an implementation of `IFilter`.
See xref:manual/filters.adoc[] for more information.
* delegate the formatting of log events to an implementation of `ILayout`.
See xref:manual/layouts.adoc[] for more information.
* only directly handle the writing of log event data to the target destination.

Appenders always have a name so that they can be referenced from a
xref:manual/configuration.adoc#configuring-loggers[logger configuration].

[#file-appenders]
== File appenders

File appenders write logs to the filesystem.
They can be further split into:

Single file appenders:::
//See xref:manual/appenders/file.adoc[] for details.

Rolling file appenders:::
//See xref:manual/appenders/rolling-file.adoc[] for details.

[#database-appenders]
=== Database appenders

The appenders write log events directly to a database.

//xref:manual/appenders/database.adoc#JdbcAppender[JDBC appender]::
Sends log events to a JDBC driver

//xref:manual/appenders/database.adoc#NoSqlAppender[NoSQL appender]::
Store log events to a document-oriented database

//See xref:manual/appenders/database.adoc[] for details.

[#network-appenders]
=== Network appenders

These appenders use simple network protocols to transmit log events to a remote host.
The supported network protocols are:

`UDP`::
`TCP`::
//These are handled by the xref:manual/appenders/network.adoc#SocketAppender[Socket Appender].

`HTTP`::
//This is handled by the xref:manual/appenders/network.adoc#HttpAppender[HTTP Appender].

`SMTP`::
//This is handled by the xref:manual/appenders/network.adoc#HttpAppender[SMTP Appender].

//See xref:manual/appenders/network.adoc[] for details.

[#delegating-appenders]
=== Delegating appenders

Delegating appenders are intended to decorate other appenders:

//xref:manual/appenders/delegating.adoc#RoutingAppender[Routing appender]::
Dynamically choose a different appender for each log event

// See xref:manual/appenders/delegating.adoc[] for details.