////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#install]
= Install Apache log4net

The preferred way to install log4net is to use our https://www.nuget.org/packages/log4net[nuget package].

Just add the following lines in your project file.
[source,xml]
----
<ItemGroup>
  <PackageReference Include="log4net" Version="*" />
</ItemGroup>
----
Now you can use log4net. See our https://github.com/apache/logging-log4net/tree/master/examples[examples].

[source,powershell]
----
dotnet add package log4net
----