# Name of container: docker-ubuntu-latest-nant
FROM ubuntu:latest

# set the maintainer of this docker image
MAINTAINER "dev@logging.apache.org"

# install nant
RUN apt-get update && apt-get install -y nant git mono-complete mono-reference-assemblies-4.0

