# Name of container: docker-ubuntu-latest-nant
FROM mono:4

# set the maintainer of this docker image
MAINTAINER "dev@logging.apache.org"

# install nant
RUN apt-get update && apt-get install -y nant git mono-reference-assemblies-4.0

