////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#forwardingappender]
= ForwardingAppender

The following example shows how to configure the `ForwardingAppender`.
The forwarding appender allows a set of constraints to be used to decorate an appender.

In this example the `ConsoleAppender` is decorated with a Threshold of level WARN. This means that an event directed to the `ConsoleAppender` directly will be logged regardless of its level, but an event directed to the `ForwardingAppender` will only be passed on to the `ConsoleAppender` if its level is WARN or higher.

This appender is used only in special circumstances.

[source,xml]
----
<appender name="ForwardingAppender" type="log4net.Appender.ForwardingAppender" >
  <threshold value="WARN"/>
  <appender-ref ref="ConsoleAppender" />
</appender>
----