////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#localsyslogappender]
= LocalSyslogAppender

`LocalSyslogAppender` writes messages to the local syslog service on Unix-like operating systems.
It uses the system's native syslog daemon and does not support remote logging.

The following example shows how to configure the `LocalSyslogAppender`.
It sends all events with Level WARN or higher.

[source,xml]
----
<appender name="LocalSyslogAppender" type="log4net.Appender.LocalSyslogAppender">
  <layout type="log4net.Layout.PatternLayout">
    <conversionPattern value="%date{MM/dd/yyyy HH:mm:ss.fff} [%thread] %-5level %logger - %message%newline" />
  </layout>
  <threshold value="WARN" />
</appender>
----

You can also specify:

* Facility (default: user)
* Identity (default: application name)

[source,xml]
----
<appender name="LocalSyslogAppender" type="log4net.Appender.LocalSyslogAppender">
  <facility>Alert</facility>
  <layout type="log4net.Layout.PatternLayout">
    <conversionPattern value="%date{MM/dd/yyyy HH:mm:ss.fff} [%thread] %-5level %logger - %message%newline" />
  </layout>
  <identity>MyApp-Canary</identity>
  <threshold value="WARN" />
</appender>
----