////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#memoryappender]
= MemoryAppender

The `MemoryAppender` stores log events in memory rather than writing them to a file or console.
It is useful for in-memory logging and can be configured to store events until the application is stopped or the memory is cleared.

It is unlikely that the `MemoryAppender` will be configured using a config file, but if you want to do it here's how.

[source,xml]
----
<appender name="MemoryAppender" type="log4net.Appender.MemoryAppender">
    <fix value="Partial" />
</appender>
----