////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#udpappender]
= UdpAppender

The `UdpAppender` sends log events over the network using the UDP protocol.
It is typically used to forward log messages to remote logging systems over a network.

The following example shows how to configure the `UdpAppender` to send events to a `remoteAddress` on the specified `remotePort`.

[source,xml]
----
<appender name="UdpAppender" type="log4net.Appender.UdpAppender">
  <localPort value="8080" />
  <remoteAddress value="224.0.0.1" />
  <remotePort value="8080" />
  <layout type="log4net.Layout.PatternLayout, log4net">
    <conversionPattern value="%-5level %logger - %message%newline" />
  </layout>
</appender>
----