# Name of container: docker-ubuntu-latest-nant
FROM microsoft/dotnet

# set the maintainer of this docker image
MAINTAINER "dev@logging.apache.org"

# install dependencies
RUN apt-get update && apt-get install -y nant git

