////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#supported-versions]
= Supported versions

.Maintenance status of selected log4net versions
[cols="2h,2,3,2,2,4"]
|===
| Version | Status | Latest release | First release | End-of-life | Notes

| 3.x
| **[active]#Active#**
| 3.2.0
| 2024-09-12
|
|

| 2.x
| **[eol]#End-of-life#**
| 2.0.17
| 2020-09-06
| 2024-09-12
| Last release to support net20 and net45

|===